recipe-app-complete/config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, :ingredients
end

recipe-app-complete/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

recipe-app-complete/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :recipes
end

recipe-app-complete/app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients
end

recipe-app-complete/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

recipe-app-complete/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    render json: @recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    # This code below has a quick demo of how to form a json object with nested ingredients on a recipe.
    # render json: @recipe, include: :ingredients
  end

  def new
    @recipe = Recipe.new
  end

  def create
    puts params
    @recipe = Recipe.create(recipe_params)
    redirect_to @recipe
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :ingredient_ids => [])
    end
end

recipe-app-complete/app/helpers/application_helper.rb
module ApplicationHelper
end

recipe-app-complete/app/helpers/recipes_helper.rb
module RecipesHelper
end

recipe-app-complete/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp071319</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

recipe-app-complete/app/views/recipes/new.html.erb
<%= form_for(@recipe) do |f| %>
  <p>
    <%= f.label :name, "Recipe Name" %>
    <%= f.text_field :name %>
  </p>

  <div>
  <%= f.collection_check_boxes(:ingredient_ids, Ingredient.all, :id, :name) do |i| %>
    <%= i.label %>
    <%= i.label { i.check_box } %>
  <% end %>
 </div>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', recipes_path %>

recipe-app-complete/app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<ul>
<% @recipe.ingredients.each do |i| %>
  <li><%= i.name %></li>
  <% end %>
</ul>